# Package Overview
package_name: regression_model

# Data Files
main_data_file: scraped_data_used_cars.csv
cars_origin_file: scraped_brands_per_country.csv
clean_data_file: clean_data.csv

# Variables
# The target variable
target: Prices

# File names to save steps of the processing
feat_pipeline_name: feature_engineering
feat_pipeline_save_file: feature_engineering_pipeline.pkl

model_name: regression_model
model_save_file: regression_model.pkl

brands_save_file: brands.pkl
fuels_save_file: fuels.pkl
trans_save_file: trans.pkl
data_size_save_file: data_size.pkl


# Input features to predict price
features:
  - Years
  - Brand
  - Kms
  - Fuel
  - Emiss_CO2
  - Cons_litres_100km
  - Transmission
  - Doors
  - Power_CV
  - Seats

luxury_cars_list:
  - lexus
  - audi
  - land-rover
  - genesis
  - cadillac
  - bmw
  - jaguar
  - mercedes
  - porsche
  - lotuscars
  - maserati
  - pagani
  - koenigsegg
  - aston
  - ferrari
  - mclaren
  - lamborghini
  - bentley
  - bugatti
  - rolls-royce  
  - tesla


# model parameters
model_params:
  colsample_bytree: 0.7
  learning_rate: 0.04
  max_depth: 20
  n_estimators: 500
  n_jobs: -1
  random_state: 42
  reg_alpha: 1.0
  reg_lambda: 0.7
  subsample: 1.0

# categorical variables with missing values
cat_vars_with_nan_frequent:
  - Brand
  - Fuel
  - Transmission

# categorical variables to encode 
freq_encode:
  - Brand

rare_brands:
  - Brand

rare_labels:
  - Fuel
  - Transmission

# numerical variables with missing values
num_vars_nan:
  - Years
  - Kms
  - Emiss_CO2
  - Cons_litres_100km
  - Doors
  - Power_CV
  - Seats


# variables to log transform
num_log_vars:
  - Kms
